[package]
name = "desktop-file-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
colored = "2.0.4"
desktop-file = { path = "../desktop-file" }
