[package]
name = "desktop-file"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = { version = "0.2.32", features = ["rust_1_64"] }
peg = "0.8.2"
thiserror = "1.0.56"

[dev-dependencies]
indoc = "2.0.4"
