[package]
name = "desktop-file"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = { version = "0.2.31", features = ["rust_1_64"] }
peg = "0.8.1"
thiserror = "1.0.48"

[dev-dependencies]
indoc = "2.0.3"
